# Generated by Django 5.1.4 on 2026-02-16 19:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код групи')),
                ('name', models.CharField(max_length=255, verbose_name='Назва групи')),
                ('min_useful_life_months', models.PositiveIntegerField(blank=True, help_text='Мінімальний строк згідно ПКУ. Null = не обмежено.', null=True, verbose_name='Мінімальний строк корисного використання (міс.)')),
                ('account_number', models.CharField(help_text='Рахунок з Плану рахунків (10х)', max_length=10, verbose_name='Рахунок обліку')),
                ('depreciation_account', models.CharField(default='131', help_text='Рахунок зносу (13х)', max_length=10, verbose_name='Рахунок зносу')),
            ],
            options={
                'verbose_name': 'Група ОЗ',
                'verbose_name_plural': 'Групи ОЗ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Інвентарний номер')),
                ('name', models.CharField(max_length=500, verbose_name='Назва')),
                ('status', models.CharField(choices=[('active', 'В експлуатації'), ('disposed', 'Списаний'), ('conserved', 'На консервації')], default='active', max_length=20, verbose_name='Статус')),
                ('initial_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Первісна вартість, грн')),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ліквідаційна вартість, грн')),
                ('current_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Залишкова (балансова) вартість, грн')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Накопичений знос, грн')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Прямолінійний'), ('reducing_balance', 'Зменшення залишкової вартості'), ('accelerated_reducing', 'Прискореного зменшення залишкової вартості'), ('cumulative', 'Кумулятивний'), ('production', 'Виробничий')], default='straight_line', max_length=30, verbose_name='Метод амортизації')),
                ('useful_life_months', models.PositiveIntegerField(verbose_name='Строк корисного використання (міс.)')),
                ('total_production_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Тільки для виробничого методу', max_digits=15, null=True, verbose_name='Загальний обсяг продукції (одиниць)')),
                ('commissioning_date', models.DateField(verbose_name='Дата введення в експлуатацію')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='Дата вибуття')),
                ('depreciation_start_date', models.DateField(help_text='Місяць, наступний за місяцем введення в експлуатацію', verbose_name='Дата початку нарахування амортизації')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Місцезнаходження')),
                ('description', models.TextField(blank=True, verbose_name='Опис / характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL, verbose_name='Матеріально відповідальна особа')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetgroup', verbose_name='Група ОЗ')),
            ],
            options={
                'verbose_name': 'Основний засіб',
                'verbose_name_plural': 'Основні засоби',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_type', models.CharField(choices=[('sale', 'Продаж'), ('liquidation', 'Ліквідація'), ('free_transfer', 'Безоплатна передача'), ('shortage', 'Нестача'), ('other', 'Інше')], max_length=20, verbose_name='Тип вибуття')),
                ('document_number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(verbose_name='Дата документа')),
                ('reason', models.TextField(verbose_name='Причина вибуття')),
                ('sale_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Заповнюється при продажу', max_digits=15, verbose_name='Сума продажу, грн')),
                ('book_value_at_disposal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Залишкова вартість на дату вибуття, грн')),
                ('accumulated_depreciation_at_disposal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Накопичений знос на дату вибуття, грн')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='assets.asset', verbose_name='Основний засіб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Вибуття ОЗ',
                'verbose_name_plural': 'Вибуття ОЗ',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('purchase', 'Придбання'), ('free_receipt', 'Безоплатне отримання'), ('contribution', 'Внесок до статутного капіталу'), ('exchange', 'Обмін'), ('self_made', 'Виготовлення власними силами'), ('other', 'Інше')], default='purchase', max_length=20, verbose_name='Тип надходження')),
                ('document_number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(verbose_name='Дата документа')),
                ('supplier', models.CharField(blank=True, max_length=500, verbose_name='Постачальник / джерело')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сума, грн')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='assets.asset', verbose_name='Основний засіб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Прихід ОЗ',
                'verbose_name_plural': 'Приходи ОЗ',
                'ordering': ['-document_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер інвентаризації')),
                ('date', models.DateField(verbose_name='Дата інвентаризації')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер наказу')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В процесі'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Місце проведення')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Голова комісії')),
                ('commission_members', models.ManyToManyField(blank=True, related_name='inventories_as_member', to=settings.AUTH_USER_MODEL, verbose_name='Члени комісії')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Інвентаризація',
                'verbose_name_plural': 'Інвентаризації',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField(verbose_name='Рік')),
                ('period_month', models.PositiveIntegerField(verbose_name='Місяць')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Прямолінійний'), ('reducing_balance', 'Зменшення залишкової вартості'), ('accelerated_reducing', 'Прискореного зменшення залишкової вартості'), ('cumulative', 'Кумулятивний'), ('production', 'Виробничий')], max_length=30, verbose_name='Метод')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сума амортизації, грн')),
                ('book_value_before', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Залишкова вартість до нарахування, грн')),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Залишкова вартість після нарахування, грн')),
                ('production_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Обсяг продукції за місяць')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Проведено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.asset', verbose_name='Основний засіб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Нарахував')),
            ],
            options={
                'verbose_name': 'Нарахування амортизації',
                'verbose_name_plural': 'Нарахування амортизації',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('asset', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_found', models.BooleanField(default=True, verbose_name='Фактична наявність')),
                ('condition', models.CharField(choices=[('good', 'Справний'), ('needs_repair', 'Потребує ремонту'), ('unusable', 'Непридатний')], default='good', max_length=20, verbose_name='Стан')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Облікова вартість, грн')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Фактична вартість, грн')),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Різниця, грн')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='assets.asset', verbose_name='Основний засіб')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.inventory', verbose_name='Інвентаризація')),
            ],
            options={
                'verbose_name': 'Рядок інвентаризації',
                'verbose_name_plural': 'Рядки інвентаризації',
                'unique_together': {('inventory', 'asset')},
            },
        ),
    ]
