# Generated by Django 5.1.4 on 2026-02-16 20:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Назва')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Коротка назва')),
                ('edrpou', models.CharField(max_length=10, unique=True, verbose_name='Код ЄДРПОУ')),
                ('address', models.TextField(blank=True, verbose_name='Юридична адреса')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Директор')),
                ('accountant', models.CharField(blank=True, max_length=255, verbose_name='Головний бухгалтер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Організація',
                'verbose_name_plural': 'Організації',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('receipt', 'Оприбуткування ОЗ'), ('depreciation', 'Нарахування амортизації'), ('disposal', 'Вибуття ОЗ'), ('revaluation', 'Переоцінка'), ('improvement', 'Поліпшення'), ('repair', 'Ремонт')], max_length=20, verbose_name='Тип операції')),
                ('date', models.DateField(verbose_name='Дата проводки')),
                ('debit_account', models.CharField(max_length=10, verbose_name='Дебет рахунку')),
                ('credit_account', models.CharField(max_length=10, verbose_name='Кредит рахунку')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сума, грн')),
                ('description', models.TextField(verbose_name='Опис операції')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('is_posted', models.BooleanField(default=True, verbose_name='Проведено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='assets.asset', verbose_name='Основний засіб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('scan', 'Скан документа'), ('photo', 'Фотографія'), ('act', 'Акт'), ('invoice', 'Накладна'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Тип файлу')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Опис')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Розмір (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.asset', verbose_name='Основний засіб')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Завантажив')),
            ],
            options={
                'verbose_name': 'Вкладення',
                'verbose_name_plural': 'Вкладення',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement_type', models.CharField(choices=[('capital', 'Капітальний ремонт (поліпшення)'), ('current', 'Поточний ремонт (витрати)'), ('modernization', 'Модернізація'), ('reconstruction', 'Реконструкція')], max_length=20, verbose_name='Тип')),
                ('date', models.DateField(verbose_name='Дата')),
                ('document_number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('description', models.TextField(verbose_name='Опис робіт')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сума, грн')),
                ('contractor', models.CharField(blank=True, max_length=500, verbose_name='Виконавець')),
                ('increases_value', models.BooleanField(default=False, help_text='Капітальний ремонт та модернізація збільшують вартість ОЗ', verbose_name='Збільшує первісну вартість')),
                ('expense_account', models.CharField(default='91', help_text='Рахунок для списання витрат (91, 92, 93, 23)', max_length=10, verbose_name='Рахунок витрат')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='assets.asset', verbose_name='Основний засіб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Поліпшення / ремонт',
                'verbose_name_plural': 'Поліпшення / ремонти',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssetRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revaluation_type', models.CharField(choices=[('upward', 'Дооцінка'), ('downward', 'Уцінка')], max_length=10, verbose_name='Тип переоцінки')),
                ('date', models.DateField(verbose_name='Дата переоцінки')),
                ('document_number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('old_initial_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Первісна вартість до переоцінки')),
                ('old_depreciation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Знос до переоцінки')),
                ('old_book_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Залишкова вартість до переоцінки')),
                ('fair_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Справедлива вартість')),
                ('new_initial_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Первісна вартість після переоцінки')),
                ('new_depreciation', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Знос після переоцінки')),
                ('new_book_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Залишкова вартість після переоцінки')),
                ('revaluation_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сума переоцінки')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluations', to='assets.asset', verbose_name='Основний засіб')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Переоцінка',
                'verbose_name_plural': 'Переоцінки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Створення'), ('update', 'Зміна'), ('delete', 'Видалення'), ('receipt', 'Оприбуткування'), ('disposal', 'Вибуття'), ('depreciation', 'Амортизація'), ('revaluation', 'Переоцінка'), ('improvement', 'Поліпшення'), ('inventory', 'Інвентаризація')], max_length=20, verbose_name='Дія')),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=500, verbose_name="Об'єкт")),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Зміни')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запис аудиту',
                'verbose_name_plural': 'Журнал аудиту',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('depreciation_done', 'Амортизація нарахована'), ('depreciation_due', 'Час нараховувати амортизацію'), ('full_depreciation', 'ОЗ повністю амортизовано'), ('inventory_due', 'Час проводити інвентаризацію'), ('shortage_found', 'Виявлено нестачу'), ('high_wear', 'Високий знос ОЗ (>90%)')], max_length=30, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name="Пов'язаний ОЗ")),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отримувач')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.organization', verbose_name='Організація'),
        ),
    ]
