# Generated by Django 5.2.11 on 2026-02-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_organization_accountentry_assetattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Назва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Місцезнаходження',
                'verbose_name_plural': 'Місцезнаходження',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Річний відсоток амортизації', max_digits=8, null=True, verbose_name='Норма амортизації (%)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='factory_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заводський номер'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacture_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік випуску'),
        ),
        migrations.AddField(
            model_name='asset',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit_of_measure',
            field=models.CharField(default='шт.', max_length=20, verbose_name='Одиниця виміру'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.location', verbose_name='Місцезнаходження'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='assets.location', verbose_name='Місце проведення'),
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipn', models.CharField(max_length=10, unique=True, verbose_name='ІПН')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІП')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Посада')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_persons', to='assets.location', verbose_name='Місце розташування')),
            ],
            options={
                'verbose_name': 'Матеріально відповідальна особа',
                'verbose_name_plural': 'Матеріально відповідальні особи',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.responsibleperson', verbose_name='Матеріально відповідальна особа'),
        ),
    ]
