# Generated by Django 5.2.11 on 2026-02-19 06:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_location_responsible_person_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='incoming_depreciation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Знос, нарахований до отримання ОЗ від іншої організації', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Вхідна амортизація (знос), грн'),
        ),
    ]
