# Generated by Django 5.2.11 on 2026-02-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_incoming_depreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetreceipt',
            name='supplier_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_as_supplier', to='assets.organization', verbose_name='Організація-постачальник'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_own',
            field=models.BooleanField(default=False, help_text='Тільки одна організація може бути позначена як власна.', verbose_name='Власна організація'),
        ),
    ]
