# Generated by Django 5.2.11 on 2026-02-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_position_and_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_as_responsible', to='assets.responsibleperson', verbose_name='Матеріально відповідальна особа'),
        ),
    ]
