# Generated by Django 6.0.1 on 2026-03-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_organization_director_accountant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='entry_type',
            field=models.CharField(choices=[('receipt', 'Оприбуткування ОЗ'), ('depreciation', 'Нарахування амортизації'), ('disposal', 'Вибуття ОЗ'), ('revaluation', 'Переоцінка'), ('improvement', 'Поліпшення'), ('repair', 'Ремонт'), ('transfer', 'Переміщення ОЗ')], max_length=20, verbose_name='Тип операції'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Створення'), ('update', 'Зміна'), ('delete', 'Видалення'), ('receipt', 'Оприбуткування'), ('disposal', 'Вибуття'), ('depreciation', 'Амортизація'), ('revaluation', 'Переоцінка'), ('improvement', 'Поліпшення'), ('inventory', 'Інвентаризація'), ('transfer', 'Переміщення')], max_length=20, verbose_name='Дія'),
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(verbose_name='Дата документа')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Підстава')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='assets.location', verbose_name='Звідки (місцезнаходження)')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='assets.responsibleperson', verbose_name='Здав (МВО)')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='assets.location', verbose_name='Куди (місцезнаходження)')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='assets.responsibleperson', verbose_name='Прийняв (МВО)')),
            ],
            options={
                'verbose_name': 'Переміщення ОЗ',
                'verbose_name_plural': 'Переміщення ОЗ',
                'ordering': ['-document_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Вартість, грн')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Примітка')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Основний засіб')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assettransfer', verbose_name='Переміщення')),
            ],
            options={
                'verbose_name': 'Позиція переміщення',
                'verbose_name_plural': 'Позиції переміщення',
                'unique_together': {('transfer', 'asset')},
            },
        ),
    ]
