# Generated by Django 5.1.4 on 2026-02-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Назва файлу')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Розмір (байт)')),
                ('status', models.CharField(choices=[('pending', 'В процесі'), ('success', 'Успішно'), ('failed', 'Помилка')], default='pending', max_length=20, verbose_name='Статус')),
                ('gdrive_file_id', models.CharField(blank=True, max_length=255, verbose_name='Google Drive ID')),
                ('gdrive_link', models.URLField(blank=True, max_length=500, verbose_name='Посилання GDrive')),
                ('error_message', models.TextField(blank=True, verbose_name='Помилка')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Автоматичний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Резервна копія',
                'verbose_name_plural': 'Резервні копії',
                'ordering': ['-created_at'],
            },
        ),
    ]
